name: etl-pipeline

on:
  # allows the pipeline to be executed manually from GitHub
  workflow_dispatch:
  
  schedule:
    # pipeline will run every day at midnight
    - cron: '0 0 * * *' 

env:
  POETRY_URL: https://install.python-poetry.org
  POETRY_VERSION: 1.8.3

jobs:
  etl_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo content
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Cache Poetry cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          # 3.10, the Python version being used, is hard-coded
          key: poetry-cache-${{ runner.os }}-3.10-${{ env.POETRY_VERSION }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          curl -sSL ${{ env.POETRY_URL }} | python - --version ${{ env.POETRY_VERSION }}
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install

      - name: Install DVC
        uses: iterative/setup-dvc@v1

      - name: Configure DVC with remote storage
        run: |
          echo "${{ secrets.BASE64_GDRIVE_CREDENTIALS_DATA }}" | base64 -d > dvc-creds.json
          dvc remote modify gdrive --local gdrive_use_service_account true
          dvc remote modify gdrive --local gdrive_service_account_json_file_path ./dvc-creds.json

      - name: Pull data from remote storage
        run: |
          dvc pull

      - name: Execute pipeline
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          TOKENIZERS_PARALLELISM: ${{ secrets.TOKENIZERS_PARALLELISM }}
        run: make etl

      - name: Push data to remote storage
        run: |
          dvc add ./data
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add data.dvc
          git commit -m "updating data and pushing to remote"
          dvc push
          git push
